// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'app': string;
  'components': string;
  'header': string;
  'setter': string;
  'workbench': string;
}
export const cssExports: CssExports;
export default cssExports;
